paths:
  /api/products/:
    get:
      summary: "obtener todos los productos"
      tags:
        - Products
      responses:
        "200":
          description: "devuelve los productos"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: "hubo un error"
    post:
      summary: "crear un producto"
      tags:
        - Products
      security:
        - cookieAuth: []
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/createProduct"
      responses:
        "200":
          description: "devuelve los productos"
        "500":
          description: "hubo un error"

  /api/products/{pid}:
    get:
      summary: obtener el producto por id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: "parametro de ruta para identificar el producto"
          schema:
            type: string
      responses:
        "200":
          description: devuelve el producto por id
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
        "500":
          description: "hubo un error"
    delete:
      summary: "eliminar un producto"
      tags:
        - Products
      security:
        - cookieAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: "parametro de ruta para identificar el carrito"
          schema:
            type: string
      responses:
        "200":
          description: "elimina un producto determinado"
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
        "500":
          description: "hubo un error"
    put:
      summary: "actualizar el producto por id"
      tags:
        - Products
      security:
        - cookieAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: "parametro de ruta para identificar el usuario ha actualizar"
          schema:
            type: string
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/updateProduct"
      responses:
        "200":
          description: "producto actualizado"
        "500":
          description: "hubo un error"

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: id autogenerado por mongo
        title:
          type: string
          description: titulo del producto
        description:
          type: string
          description: descripcion del producto
        code:
          type: number
          description: codigo del producto
        category:
          type: string
          description: categoria del producto
        price:
          type: number
          description: precio del producto
        thumbnails:
          type: array
          description: array de imagenes del producto
        stock:
          type: number
          description: stock del producto
        status:
          type: boolean
          description: status del producto
      example:
        _id: ObjectId("asdasdasd")
        title: "Mantel"
        description: "Mantel rojo"
        code: 1
        category: "Cocina"
        price: 12
        thumbnails: ["foto.png"]
        stock: 12
        status: true
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: titulo del producto
        description:
          type: string
          description: descripcion del producto
        code:
          type: number
          description: codigo del producto
        category:
          type: string
          description: categoria del producto
        price:
          type: number
          description: precio del producto
        thumbnails:
          type: array
          description: array de imagenes del producto
        stock:
          type: number
          description: stock del producto
        status:
          type: boolean
          description: status del producto
      example:
        title: "Mantel"
        description: "Mantel rojo"
        code: 1
        category: "Cocina"
        price: 12
        thumbnails: ["foto.png"]
        stock: 12
        status: true
    createProduct:
      type: object
      properties:
        title:
          type: string
          description: titulo del producto
        description:
          type: string
          description: descripcion del producto
        code:
          type: number
          description: codigo del producto
        category:
          type: string
          description: categoria del producto
        price:
          type: number
          description: precio del producto
        thumbnails:
          type: array
          description: array de imagenes del producto
        stock:
          type: number
          description: stock del producto
        status:
          type: boolean
          description: status del producto
      example:
        title: "Mantel"
        description: "Mantel rojo"
        code: 1
        category: "Cocina"
        price: 12
        thumbnails: ["foto.png"]
        stock: 12
        status: true
    securitySchemes:
      cookieAuth:
        type: apiKey
        in: cookie
        name: Codercookie
